имя:  Сборка 
на: 
  push: 
    ветки: 
      -  main 
  pull_request: 
    типы: [ открыт , синхронизация , повторно открыт ]
 задания: 
  sonarqube: 
    имя:  SonarQube 
    работает на:  ubuntu-latest 
    шаги: 
      -  использует:  actions/checkout@v4 
        с: 
          fetch-depth:  0   # Поверхностные клоны следует отключить для большей релевантности анализа 
      -  имя:  SonarQube  Scan 
        использует:  SonarSource/sonarqube-scan-action@v6 
        env: 
          SONAR_TOKEN:  ${{  secrets.SONAR_TOKEN  }}
